core/urls.py
from django.conf.urls import url
from django.contrib import admin
#from playme.core import views as core_views
from core import views as core_views
from django.contrib.auth import views as auth_views
from django.conf import settings

# SET THE NAMESPACE!
app_name = 'core'


urlpatterns = [
    url(r'^$', core_views.index, name='index'),
    url(r'signup/$', core_views.signup, name='signup'),
    url(r'snakeyes/$', core_views.snakeyes, name='snakeyes'),
    url(r'snakedone/$', core_views.snakedone, name='snakedone'),
    url(r'war/$', core_views.war, name='war'),
    url(r'peace/$', core_views.peace, name='peace'),
    url(r'^account/$', core_views.account, name='account'),
    url(r'^transfer/$', core_views.transfer, name='transfer'),
    url(r'^profile/$', core_views.view_profile, name='profile'),
    url(r'^login/$', auth_views.login, {'template_name': 'core/login.html'}, name='user_login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/play/'}, name='logout'),
    url(r'^edit_account/$', core_views.edit_account, name='edit_account'),
    url(r'^edit_profile/$', core_views.edit_profile, name='edit_profile'),
    url(r'^change_password/$', core_views.change_password, name='change_password'),
]

playme/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from .views import home


urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^play/',include('core.urls', namespace='core')),
    url(r'^admin/', admin.site.urls),
]

playme/views.py
from django.shortcuts import render

def home(request):
    return render(request,"home.html", {})

playme/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<!-- ROOT BASE FILE -->
<html>
  <head>
    <meta charset="utf-8">
    <title>Play Me Fun</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <!-- Local CSS  -->
    <link rel="stylesheet" href="{% static "css/master.css"%}">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">

          {# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'home' %}">DJANGO</a></li>
          <li><a class="navbar-link" href="{% url 'core:signup' %}">Register</a></li>

          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'core:logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'core:user_login' %}">Login</a></li>
          {% endif %}

        </ul>
      </div>
    </nav>
    <div class="container">
        {% block content %}

        {% endblock %}


    </div>

  </body>
</html>

playme/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Play Me{% endblock %}

{% block content %}
<div class="thumbnail">
      <img src="{% static "img/Casino1.jpg" %}" alt="something" />
</div>
{% endblock %}