core/urls.py
from django.conf.urls import url
from django.contrib import admin
#from playme.core import views as core_views
from core import views as core_views
from django.contrib.auth import views as auth_views
from django.conf import settings

# SET THE NAMESPACE!
app_name = 'core'


urlpatterns = [
    url(r'^$', core_views.index, name='index'),
    url(r'signup/$', core_views.signup, name='signup'),
    url(r'snakeyes/$', core_views.snakeyes, name='snakeyes'),
    url(r'snakedone/$', core_views.snakedone, name='snakedone'),
    url(r'war/$', core_views.war, name='war'),
    url(r'peace/$', core_views.peace, name='peace'),
    url(r'^account/$', core_views.account, name='account'),
    url(r'^transfer/$', core_views.transfer, name='transfer'),
    url(r'^profile/$', core_views.view_profile, name='profile'),
    url(r'^login/$', auth_views.login, {'template_name': 'core/login.html'}, name='user_login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/play/'}, name='logout'),
    url(r'^edit_account/$', core_views.edit_account, name='edit_account'),
    url(r'^edit_profile/$', core_views.edit_profile, name='edit_profile'),
    url(r'^change_password/$', core_views.change_password, name='change_password'),
]

playme/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from .views import home


urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^play/',include('core.urls', namespace='core')),
    url(r'^admin/', admin.site.urls),
]

core/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    description = models.CharField(max_length=100, default='')
    city = models.CharField(max_length=100, default='')
    website = models.URLField(default='')
    phone = models.IntegerField(default=0)
    betting_balance = models.FloatField(default=0)
    bank_balance  = models.FloatField(default=0)
    image = models.ImageField(upload_to='profile_image', blank=True)

    def __str__(self):
        return self.user.username

def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)

core/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from django.contrib.auth.models import User
from .models import UserProfile

class ProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('description', 'city', 'website', 'image')

class BankingForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('bank_balance',)


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2' )

    def save(self,commit=True):
        user = super(SignUpForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()
        return user

class EditAccountForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'password' )

core/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.core.urlresolvers import reverse
from django.contrib.auth import login, authenticate, update_session_auth_hash
from django.contrib.auth.forms import (
        UserCreationForm,
        UserChangeForm,
        PasswordChangeForm
        )
from django.contrib.auth.models import User
from django.conf import settings
from django.shortcuts import render, redirect
from core.forms import ( EditAccountForm, SignUpForm,
                        ProfileForm,BankingForm
                        )
from core.models import UserProfile
from django.views.generic import (TemplateView,ListView,
                                  DetailView,CreateView,
                                  UpdateView,DeleteView)

# Create your views here.

def peace(request):
    if request.method == 'POST':
        adjust = float(request.POST['betResult'])
        udata = UserProfile.objects.get(user=request.user)
        udata.user = request.user
        udata.betting_balance += adjust
        udata.save()
        args = {'form':request.POST}
        return render(request,'core/peace.html',args)
    else:
        print('Reloading War')
        return render(request,'core/war.html',{})

def snakedone(request):
    if request.method == 'POST':
        adjust = float(request.POST['betResult'])
        udata = UserProfile.objects.get(user=request.user)
        udata.user = request.user
        udata.betting_balance += adjust
        udata.save()
        args = {'form':request.POST}
        return render(request,'core/snakedone.html',args)
    else:
        print('Reloading War')
        return render(request,'core/snakeyes.html',{})


def view_profile(request):
    if request.method == 'POST':
        form = BankingForm(request.POST, instance=request.user.userprofile)
        udata = UserProfile.objects.get(user=request.user)
        if form.is_valid():
            save_data = form.save(commit=False)
            save_data.user = request.user
            udata.user = request.user
            udata.bank_balance -= save_data.bank_balance
            udata.betting_balance += save_data.bank_balance
            udata.save()
            return redirect(reverse('core:profile'))
        return redirect(reverse('core:profile'))
    else:
        form = UserProfile.objects.get(user=request.user)
        args = {'form':form}
        return render(request,'core/profile.html',args)


def transfer(request):
    if request.method == 'POST':
        form = BankingForm(request.POST, instance=request.user.userprofile)
        udata = UserProfile.objects.get(user=request.user)
        if form.is_valid():
            save_data = form.save(commit=False)
            save_data.user = request.user
            udata.user = request.user
            udata.bank_balance -= save_data.bank_balance
            udata.betting_balance += save_data.bank_balance
            udata.save()
            return redirect(reverse('core:profile'))
    else:
        udata = UserProfile.objects.get(user=request.user)
        form = BankingForm(instance=udata)
        args = {'form': form}
    return render(request, 'core/banking.html', args)


def edit_profile(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST, instance=request.user.userprofile)
        if form.is_valid():
            save_data = form.save(commit=False)
            save_data.user = request.user
            save_data.save()
            return redirect(reverse('core:profile'))
    else:
        udata = UserProfile.objects.get(user=request.user)
        form = ProfileForm(instance=udata)
        args = {'form': form}
    return render(request, 'core/edit_profile.html', args)



def index(request):
    return render(request,"core/index.html", {})

def war(request):
    return render(request,"core/war.html", {})

def snakeyes(request):
    return render(request,"core/snakeyes.html", {})


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return render(request,"core/index.html", {})
    else:
        form = SignUpForm()
    return render(request, 'core/signup.html', {'form': form})

def edit_account(request):

    if request.method == 'POST':
        form = EditAccountForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return render(request,"core/account.html", {})
    else:
        form = EditAccountForm(instance=request.user)
        args = {'form':form}
        return render(request,'core/edit_account.html', args)

def change_password(request):

    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return render(request,"core/profile.html", {})
    else:
        form = PasswordChangeForm(user=request.user)
        args = {'form':form}
        return render(request,'core/change_password.html', args)

def account(request):
    args = {'user':request.user}
    return render(request, 'core/account.html', args)

playme/views.py
from django.shortcuts import render

def home(request):
    return render(request,"home.html", {})

playme/templates/core/Xedit_profile.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}
  <h2>Edit Profile Details</h2>
  <form method="post">
    {% csrf_token %}
      {% for field in form %}
           <div class="row">
              {{ field.errors }}
              {{ field.label_tag }} {{ field }}
              {% if field.help_text %}
              <div class="row">
                    {{ field.help_text }}
              </div>
              {% endif %}
          </div>
      {% endfor %}
      <button type="submit">Edit</button>
    </form>
  {% endblock %}

playme/templates/core/banking.html
{% extends 'core/base.html' %}
{% load static %}



{% block title %}Banking{% endblock %}

{% block content %}
<h2>Transfer Funds</h2>
<h3>How much do you want to take out you bank to increase your betting balance?</h3>
<form method="post">
  {% csrf_token %}
    {% for field in form %}
         <div class="row">
            {{ field.errors }}
            {{ field.label_tag }} {{ field }}
            {% if field.help_text %}
            <div class="row">
                  {{ field.help_text }}
            </div>
            {% endif %}
        </div>
    {% endfor %}
    <button type="submit" class="btn btn-success">Transfer</button>
  </form>
{% endblock %}

playme/templates/core/edit_account.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
  <h2>Edit Account Details</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Edit</button>
  </form>
{% endblock %}

playme/templates/core/edit_profile.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
  <h2>Edit {{ user }}  Details</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Edit</button>
  </form>
{% endblock %}

playme/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}Play Me{% endblock %}

{% block content %}
  <h2>Index:PLAY - Welcome</h2>
  <div class="container">
      <div class="row v-center">
          <div class="col-xs-6">
              <a href="/play/snakeyes/" class="thumbnail">
              <img src="{% static "img/snake_eyes.jpg" %}" alt="Snake Eyes" />
              </a>
          </div>
          <div class="col-xs-6">
              <a href="/play/war/" class="thumbnail">
                    <img class="vmiddle" src="{% static "img/war.png" %}" alt="War" />
              </a>
          </div>
      </div>
  </div>
{% endblock %}

playme/templates/core/login.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}Login{% endblock %}

{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock %}

playme/templates/core/navbar.html
<nav class="navbar navbar-default techfont custom-navbar">
    <div class="container">
      <ul class="nav navbar-nav">
        <li><a class='navbar-brand bigbrand' href="/play/">Play Me</a></li>
        <li class="nav navbar-nav">
          {% if request.get_full_path == "/play/profile/" %}
          <a href="{% url 'core:edit_profile' %}">Edit Profile</a>
          {% endif %}</li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
          <li>
            <a href="/play/snakeyes/" >Snake Eyes</a>
          </li>
          <li>
            <a href="/play/war/">War</a>
          </li>
          <li>
            <a href="/play/logout/" >Log out</a>
          </li>
          <li class="dropdown" id="menu1">
                  <a class="dropdown-toggle" data-toggle="dropdown" href="#menu1">
                  Welcome: {{ user.username }}
                  <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                      <li><a href="/play/account">Your Account</a></li>
                      <li><a href="/play/edit_account/">Edit Account</a></li>
                      <li><a href="/play/change_password/">Change Password</a></li>
                      <li class="divider"></li>
                      <li><a href="/play/profile/">Profile</a></li>
                  </ul>
              </li>

        {% else %}
            <li><a class='nav navbar-right' href="/play/signup" >Register</a></li>
            <li><a class='nav navbar-right' href="/play/login" ><span class="glyphicon glyphicon-user"></span></a></li>
                  {% endif %}

      </ul>
  </div>
</nav>

playme/templates/core/peace.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}Peace{% endblock %}

{% block content %}
  <h2>Thank you for playing war</h2>
  <div class="container">
      <div class="row v-center">
          <div class="col-xs-6">
            {% if form.betResult|add:"0" > 0 %}
              <h4>Congratulations {{ user}}</h4>
              <h4>That little venture netted you {{ form.betResult }} dollars</h4>
              <br>
            {% else %}
              <h4>Unfortunately today might not be your day</h4>
              <h4>The House took {{ form.betResult }} dollars</h4>
              <br>
              <p>Would you like to play again?</p>
            {% endif %}
          </div>
          <div class="col-xs-6">
              <a href="/play/war/" class="thumbnail">
                    <img class="vmiddle" src="{% static "img/war.png" %}" alt="War" />
              </a>
          </div>
      </div>
  </div>
{% endblock %}

playme/templates/core/profile.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
  <h2>{{ user }} Profile Details </h2>
<p>
  <table width="30%">
    <col style="width:25%">
    <col style="width:25%">
    <tr>
      <td>User</td><td> {{ user }} </td>
    </tr>
    <tr>
      <td>Description</td><td>{{ form.description }}</td>
    </tr>
    <tr>
      <td>City</td><td> {{ form.city }} </td>
    </tr>
    <tr>
      <td>Website</td><td>{{ form.website }}</td>
    </tr>
    <tr>
      <td>Betting Balance</td><td>{{ form.betting_balance }}</td>
    </tr>
    <tr>
      <td>Bank Balance</td><td>{{ form.bank_balance }}</td>
    </tr>
    <tr>
      <td>Image</td><td>{{ form.image }}</td>
    </tr>
  </table>

</p>
<!-- Indicates a successful or positive action -->
<!-- <a href="/play/transfer/"><button type="button" class="btn btn-success">Get Funds</button></a> -->
<!-- Trigger the modal with a button -->
<button type="button" class="btn btn-info btn-success" data-toggle="modal" data-target="#myModal">Get Funds</button>

<!-- Modal -->
<div class="modal fade" id="myModal" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">You can't win if you don't play</h4>
      </div>
      <div class="modal-body">
        <h2>Transfer Funds</h2>
        <h3>How much do you want to take out of your bank to increase your betting balance?</h3>
        <form method="post">
          {% csrf_token %}
            Bank Balance = {{ form.bank_balance }} <br>
            Transfer:<br> <input type="text" name="bank_balance"><br><br>
            <button type="submit" class="btn btn-success">Transfer</button>
          </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>


{% endblock %}

playme/templates/core/signup.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}

playme/templates/core/snakedone.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}Snake Eyes{% endblock %}

{% block content %}
  <h2>Thank you for playing Snake Eyes</h2>
  <div class="container">
      <div class="row v-center">
          <div class="col-xs-6">
            {% if form.betResult|add:"0" > 0 %}
              <h4>Congratulations {{ user}}</h4>
              <h4>That little venture netted you {{ form.betResult }} dollars</h4>
              <br>
            {% else %}
              <h4>Unfortunately today might not be your day</h4>
              <h4>The House took {{ form.betResult }} dollars</h4>
              <br>
              <p>Would you like to play again?</p>
            {% endif %}
          </div>
          <div class="col-xs-6">
              <a href="/play/snakeyes/" class="thumbnail">
                    <img class="vmiddle" src="{% static "img/snake-eyes.jpg" %}" alt="Snake Eyes" />
              </a>
          </div>
      </div>
  </div>
{% endblock %}

playme/templates/core/snakeyes.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}Snake Eyes{% endblock %}

{% block head_inject %}
<script type="text/javascript">
  var player1_wins = 0 ;
  var currentBet = 0;
  var player2_wins = 0 ;
  var dice_roll = -99 ;
  var leader = 0 ;
  var betSize = 10 ;
  var warBalance = 1.23 ;
</script>

{% endblock %}

{% block content %}

{% verbatim dice %}
<div class="col-lg-6" >
  <h1>Status & Rules</h1><br>
  <h4>Status</h4>
  <p id="betsize"></p>
  <p id="yourBet"></p>
  <p id="currentwinner"></p>
  <p id="player1"></p>
    <p id="player2"></p><br>
  <h4>Rules</h4>
  <p>We roll the dice, you bet the outcome, simple! However if you roll a double, the dice are rolled again,
    and if you roll 'snake-eyes'(Two ones, you lose!).</p>
    <p>The default bet is $10, but you can reset that below.</p>
    <br>
    <h4>Payouts</H4>
    <p>The house pays 190% of the cumulative winnings</p><br>
    <button type="button" class="btn btn-info btn-success" data-toggle="modal" data-target="#myModal">Set Bet Size</button>
    <button ng-if="game.winner" type="button" class="btn btn-success" onclick="settleUp()">Pay out</button>
</div>
<div class="col-lg-6" >
  <div class="placeBet">
    <br><br>
    <h4>Place your bet and then roll the dice.</h4>
    <select id="selectedBet" >
      <option value="3">3</option>
      <option value="4">4</option>
      <option value="5">5</option>
      <option value="6">6</option>
      <option value="7">7</option>
      <option value="8">8</option>
      <option value="9">9</option>
      <option value="10">10</option>
      <option value="11">11</option>
    </select>
    <br><br><br>

  </div>
  <div class="Daro">
    <div id="daroResults">

    </div>

  </div>
</div>
<div class="setBet">
  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">The more you play the more we pay</h4>
        </div>
        <div class="modal-body">
          <h2>Set Bet Size</h2>
          <h3>OK so what is it going to be?</h3>
          <form method="post">
            {% csrf_token %}
              Bet (between $1 and $50): <input type="number" id="myBet" min="1" max="50">
              <button type="submit" class="btn btn-success" data-dismiss="modal" onclick="setBet()" >Place Bet</button>
            </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-success" data-dismiss="modal">Just the default bet please</button>
        </div>
      </div>
    </div>
  </div>
</div>

<script type='text/javascript' src='/static/js/d6.js'></script>
<script type="text/javascript" src="/static/js/daro.js"></script>

<script type='text/javascript'>
function incrementScore(){
  getBet();
  leader = "The House"
  if (dice_roll == currentBet){
    player1_wins += 1;
    leader = "You"
  }else {
    player2_wins += 1 ;
  }
  document.getElementById("betsize").innerHTML = "Each bet is "+betSize;
  document.getElementById("yourBet").innerHTML = "Current bet is "+currentBet;
  document.getElementById("currentwinner").innerHTML = "This rounds winner is "+leader;
  document.getElementById("player1").innerHTML = "Your score = "+player1_wins;
  document.getElementById("player2").innerHTML = "House score = "+player2_wins;
}
function setBet(){
  betSize = $('#myBet').val();
  document.getElementById("betsize").innerHTML = "Each bet is "+betSize;
}
function getBet(){
  currentBet = $('#selectedBet').val();
}
function settleUp(){
  console.log("Settling up");
  console.log(player1_wins, player2_wins);
  if (player1_wins > player2_wins){
    warBalance = Math.floor((player1_wins-player2_wins)*1.9*betSize)
    console.log("player1_wins"+warBalance);
    console.log(player1_wins, player2_wins, betSize);
  } else {
    warBalance = Math.floor((player2_wins-player1_wins)*betSize)
    console.log("player2_wins"+warBalance);
    console.log(player1_wins, player2_wins, betSize);
    warBalance = warBalance*-1
  }
  document.getElementById('betResult').value = warBalance;
  console.log(warBalance);
  leader=1;
  document.forms.hiddenForm.submit()
}

</script>
{% endverbatim dice%}
<div id="hiddenForm" style="display: none" class="visibility=hidden">
  <form class="" action="/play/snakedone/" name="hiddenForm" method="post">
    {% csrf_token %}
    <input type="hidden" name="betResult" id="betResult" value="snakeBalance">
    <button type="submit" name="betBalance">Update Balance</button>
  </form>
</div>

{% endblock %}

playme/templates/core/test.html
<!DOCTYPE html>
{% load static from staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Test JS Directory</title>
  </head>
  <body>

  </body>
  <script type="text/javascript" src="/static/js/test.js">

  </script>
</html>

playme/templates/core/userprofile_detail.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
  <h2>Edit Account Details</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Edit</button>
  </form>
{% endblock %}